### ISSUE TITLE
Зависает (черный экран) при запуске

### ISSUE THREAD

**Issue by xlo1911** [unxed/putty4far2l#1]
После обновления fa2l (сборка от 21.12.2020 и более поздние) при запуске из putty4far2l (Windows 10 LTSC) отображается черный экран и зависает. При запуске из оригинального putty все работает.

**Comment by unxed** [comment]
Ага, протокол экстеншнов чуть изменился вот тут https://github.com/elfmz/far2l/commit/08b00749fb8d7ae8fc035906b335d9c2600dff86

[Поправил](https://github.com/unxed/putty4far2l/commit/9a433f3d6c16f7bc8fece613c05e6e1da50f4f2d), перепроверьте, пожалуйста

**Comment by xlo1911** [comment]
Всё работает. Спасибо!
