### ISSUE TITLE
Putty is making a putty.log 

### ISSUE THREAD

**Issue by vb0** [unxed/putty4far2l#5]
Using the "putty.exe for x86" linked from README on Windows 10 it's creating a putty.log without any logging configured, with a content like below. This is triggered by using far2l remotely and I presume it's just a leftover from some debug. Otherwise everything works great, this is really useful.

>  Up     13   28   28 0  
>  Down   37   75   75 1

**Comment by unxed** [comment]
Thanks for report! Check now, please.

**Comment by vb0** [comment]
Fix confirmed, outstanding - from bug report to a fixed binary in 13 minutes that must be a record in the history of software development! Thank you!
